### ISSUE TITLE
embedding OPC UA client into CMS framework

### ISSUE THREAD

**Issue by alamsha** [uaf/uaf#101]
"The intent of (Py)UAF is to facilitate a web-browser-like experience for the plant floor."
---------------------------

A CMS platform provides the right framework to build dyanmic web pages. Is it possible to embed OPC UA client into a open source CMS and build "Iot enabled SCADA" web sites?. BTW, i am trying to do this with couch CMS. You can also try and share your experience with your favourite CMS platform.

Django might be a right platform to build dynamic web pages with  (Py)UAF.

**Comment by WimPessemier** [comment]
Several people have used Python web frameworks + pyUAF to build dynamic HMI/SCADA web appiications. At least some of them use the callback arguments of the pyuaf.client.Client methods to create MonitoredItems, to update the web pages dynamically via web sockets. 
So yes, it certainly can be done.
