### ISSUE TITLE
UAF use in LabView

### ISSUE THREAD

**Issue by felixkretschmer** [uaf/uaf#116]
Did someone already try to use UAF in LabView? Is it possible to import DLLs and header-Files and use the UAF methods?

**Comment by WimPessemier** [comment]
Haven't tried this, feel free to post your experiences if you test it...

**Comment by felixkretschmer** [comment]
Well, this does not seem to work because the functions of the DLLs are not exported.

**Comment by WimPessemier** [comment]
Hmm the manually developed functions *are* exported in Windows, but perhaps not the functions generated by SWIG. Maybe you can force SWIG to export the functions, you'll have to check the SWIG docs for that...
