### ISSUE TITLE
DataChangeNotification object is not serialized 

### ISSUE THREAD

**Issue by HimanshuDobaria** [uaf/uaf#136]
Hi Wim,

We want to persist DataChangeNotification object, we tried to serialize in JSON and Pickle format but it didn't work and we got below error.

Using Pickle :
TypeError: can't pickle SwigPyObject objects

Using JSON :
TypeError: <pyuaf.client.DataChangeNotification( - clientHandle       : 0
                                     - status             : Good
                                     - data               : 72.0000000078)> is not JSON serializable

Please help to resolve this issue.

**Comment by WimPessemier** [comment]
Hello,
You cannot pickle this object, because it is not a native Python object. It is a wrapped Swig object, as the error says.
So you have to convert it manually (e.g. into a dict) and serialize that.
