### ISSUE TITLE
browse / rebrowse

### ISSUE THREAD

**Issue by monstersintokyo** [uaf/uaf#28]
Hey Wim,

I have a question or idea regarding the browse functionality.
First off: the browse functionality is great! ;-)

We use it to dynamically browse machine modules, that are part of our machine line. If there are any machine module nodes, we create new UA client instances; they immediately start to monitor the state of those modules etc.
Now the issue here is the following: if we start the ua client before the ua server is started, browse will not find any module subnodes (naturally). In a default case this should not happen in our environment. Still I think about making sure, that even the not so default case could work.

When using monitored items, PyUAF will make sure that those nodes are monitored when the server comes online. The server can even go offline in between, come online again; it will simply work.

I could mimic that behavior manually. We are monitoring the server state. Rebrowse when server is online, kill the old module state clients if there are any, create new ones, restart monitoring.

But maybe in a future version of the PyUAF there could be something like a "monitored" browse functionality:
You register some nodes that you want to browse / rebrowse when the server is online. This will call some callback (just like monitored items do). In the callback you could do some custom code, like creating new clients in our case.

**Comment by monstersintokyo** [comment]
Hey Wim,

totally forgot to answer this ticket. Sorry :-/
After browsing through our webserver code the "connectionStatusChanged" callback should indeed completely suffice.

As always, thank you!

**Comment by WimPessemier** [comment]
No worries :) 
Thanks for the feedback!
