### ISSUE TITLE
Build does not work with VS2013

### ISSUE THREAD

**Issue by pfpmeijers** [uaf/uaf#43]
The macro setUnifiedAutomationSdkCompilerDir in the cmake script does not contain a case for MSVC12. After mapping this to vs2010sp1, the cmake goes OK. But then compilation gives error in namespacearray.cpp::getSimplifiedUri. The error says that std::ptr_fun is not defined.
After commenting out the line with this std:ptr call (it only does a string to lower case conversion), I am stuck with link errors: mismatch detected for '_MSC_VER': value '1600' doesn't match value '1800' in client.obj. Now I am lost ...
Any plans to add support for latest Visual Studio version? Or is something else wrong in my build procedure?

**Comment by WimPessemier** [comment]
It took a while, but the dlls are now copied automatically by default.
Use the -DCOPY_SDK_LIBS=OFF flag to keep the old behaviour (i.e. in which the dlls have to be copied manually).
