### ISSUE TITLE
Make error on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by LBeaufore** [uaf/uaf#44]
We are attempting to test PyUAF with an Ubuntu 14.04.1 virtual machine, and we have run into some problems in the make step. For background, our kernel version is "3.13.0-36-generic", and our GCC version is 4.8.2.

I have run the cmake step with apparent success:

cmake ../src -DUASDK=/tmp/sdk -DCMAKE_LIBRARY_PATH=/usr/lib/python2.7/config-x86_64-linux-gnu/ -DCMAKE_INCLUDE_PATH=/usr/include/python2.7 -DUASTACK_WITH_HTTPS=ON

-- ========== SUMMARY ==========
-- SDK was found    : TRUE (/tmp/sdk)
-- SWIG was found   : TRUE (/usr/bin/swig2.0)
-- Python was found : TRUE (/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so)
-- Options          : UASTACK_WITH_HTTPS = ON
-- This means that the UAF will be built, including Python wrappers
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/uaf-1.10/build

However, running make after this produces the following error:

make

Linking CXX shared library /tmp/uaf-1.10/lib/libuafutil.so
/usr/bin/ld: /tmp/sdk/lib/libuabase.a(uastring.cpp.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
/tmp/sdk/lib/libuabase.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: **\* [/tmp/uaf-1.10/lib/libuafutil.so] Error 1
make[1]: **\* [uaf/util/CMakeFiles/uafutil.dir/all] Error 2
make: **\* [all] Error 2

This persists after changing
  set(CMAKE_CXX_FLAGS "-Wall -Wno-unused-function -Wno-comment")
to
  set(CMAKE_CXX_FLAGS "-Wall -Wno-unused-function -Wno-comment -fPIC")

in src/UafMacros.cmake

**Comment by mshemuni** [comment]
Not sure if it's what happened here for me but, I tried to install sdk systemwide. That's why I copied all lib files to /lib64 and made a link for each file in /lib. That may help.
