### ISSUE TITLE
Connecting to opc ua servers with certificates

### ISSUE THREAD

**Issue by fgroes** [uaf/uaf#46]
I asked the following question to the author of the library by email, i thought i would share the results to maybe help out other people as well.

Hello,

i am trying to connect to an opc ua server with your module.

I keep getting the following error:

pyuaf.util.errors.OtherError: Could not load the client certificate - The requested session could not be created (Connection failed)

maybe you have an idea, what is wrong.

I did get a connection with the same configuration using the UaExpert Software from unified automation, the same company that has written the opc ua c++ sdk your module is wrapping, so it should not be too hard to get this going.

The UaExpert created the certificate file used below. I am just not sure, how i can tell the client where to find the file. The approach below does not seem to work.

Maybe you could write up an example using a certificate, the current examples do not show any security settings changes afaik. I am shure this would be of interest to other people as well.

thx,
Fritz

```python
import pyuaf


class PClient(pyuaf.client.Client):

    def connectionStatusChanged(self, info):
        print(info)


cert_file_name = r'D:\...\cert_1.cer'`

client_settings = pyuaf.client.settings.ClientSettings()
client_settings.applicationName = 'myClient'
client_settings.clientCertificateAbsoluteFileName = cert_file_name

client = PClient(client_settings)

security_settings = pyuaf.client.settings.SessionSecuritySettings()
security_settings.securityPolicy = pyuaf.util.securitypolicies.UA_Basic128Rsa15
security_settings.messageSecurityMode = pyuaf.util.messagesecuritymodes.Mode_SignAndEncrypt
security_settings.userTokenType = pyuaf.util.usertokentypes.UserName
security_settings.userName = 'TEST'
security_settings.userPassword = 'TEST'

session_settings = pyuaf.client.settings.SessionSettings()

session_security_settings_vector = pyuaf.client.settings.SessionSecuritySettingsVector()
session_security_settings_vector.append(security_settings)
session_settings = pyuaf.client.settings.SessionSettings()
session_settings.securitySettingsList = session_security_settings_vector

client_connection_id = client.manuallyConnectToEndpoint('opc.tcp://...:4841', sessionSettings=session_settings)
```

**Comment by WimPessemier** [comment]
It's now merged into the master branch. See changelog.
