### ISSUE TITLE
Alarms with no nodes

### ISSUE THREAD

**Issue by LBeaufore** [uaf/uaf#63]
There appears to be alarms with and without nodes in OPC UA, I only see examples of how to deal with node based alarms in PyUAF's "easiest client tutorial". Is there a method to dealing with alarms without nodes?

Thanks!

**Comment by WimPessemier** [comment]
I'm not sure what you mean by "alarms without nodes"... AFAIK: alarms are events, and events are transferred by monitored items. So you'll need at least one "item" (node) to monitor.

**Comment by LBeaufore** [comment]
I noticed these in the Unified Automation test server, under Root, Objects, Demo, 004_Events, AlarmsNoNodes. Maybe I am misunderstanding the structure?
