### ISSUE TITLE
Core dump after read value with empty Text or LocalizedText

### ISSUE THREAD

**Issue by jorrita** [uaf/uaf#70]
It seems that pyuaf has some trouble with reading attributes of a node that have an empty string as value.

A simple reproduction can be done with uaservercpp. Note that I encountered the same problem (in our own service) when the value of a node contained an empty string. 
In pyuaf do:

```
>>> statenode = Address(NodeId("AirConditioner_1.State", 3), 'urn:UnifiedAutomation:UaServerCpp')
>>> result = myClient.read([statenode], attributeId=pyuaf.util.attributeids.Description)
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

**Comment by WimPessemier** [comment]
Hi, the bugs should be fixed. 
There were some cases where SDK UaStrings were converted to std::strings without checking if the UaStrings represented a NULL value.
